In [1]:
import numpy as np
from scipy import linalg as la
import matplotlib.pyplot as plt; plt.style.use('dark_background')
np.set_printoptions(suppress=True) 

def bags(setA):
    # setA is the given ordered set A ={a_1,....,a_N}
    # output is the optimal values of both players 
    # and the optimal action of the player who has the turn
    
    dim=len(setA)
    # NOTE THIS IS DIFFERENT NOTATION THAN THE ONE USED IN CLASS
    # (optimal) value when k bags left after i rights
    # first component of "optimal" is k-1, second is i
    value_first=np.zeros((dim,dim)) # value of the player playing
    value_second=np.zeros((dim,dim)) # value of the player waiting
      
    # (optimal) decision when k bags left after i rights
    # decision = 1 means take the left most one
    # decision = 0 means take the right most one
    decision=np.zeros((dim,dim)) 

    # single element set first , i.e., k=1
    for i in range(dim):
        value_first[0][i]=setA[i]        
    for k in range(1,dim):
        for i in range(dim-k):
            left=setA[i]+value_second[k-1][i+1]
            right=setA[i+k]+value_second[k-1][i]
            value_first[k][i]= max(right , left)
            if left >= right :
                decision[k][i]=1
                value_second[k][i]=value_first[k-1][i+1]
            else:
                value_second[k][i]=value_first[k-1][i] 
    return value_first , value_second , decision

def printing_decisions(setA):   
    dim=len(setA)
    
    vf, vs, dec = bags(setA)
    total_lefts=0
    for k in reversed(range(dim)):
        if dec[k][total_lefts] ==1:
            print("with %d bags remaining, it is optimal  to pick the left most bag"%(k+1))
            print("Picked value is", setA[0])
            setA.pop(0)
            print("Remaining set is", setA)
            total_lefts +=1
        else:           
            print("with %d bags remaining, it is optimal  to pick the right most bag"%(k+1))
            print("Picked value is", setA[-1])
            setA=setA[:-1]
            print("Remaining set is", setA)
               

In [12]:
A=[5,4,3,20,5,8,7,19,1]
d=len(A)

F , S, D = bags(A)

print(D)

print(A)
print()
print('The optimal value for the starter is',F[d-1][0])
print('The optimal value for the second player is',S[d-1][0])
print()
printing_decisions(A)

print(np.sum(A))

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 1. 1. 0. 1. 0. 0.]
 [0. 1. 0. 1. 0. 1. 0. 0. 0.]
 [1. 0. 1. 1. 1. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0.]]
[5, 4, 3, 20, 5, 8, 7, 19, 1]

The optimal value for the starter is 21.0
The optimal value for the second player is 51.0

with 9 bags remaining, it is optimal  to pick the left most bag
Picked value is 5
Remaining set is [4, 3, 20, 5, 8, 7, 19, 1]
with 8 bags remaining, it is optimal  to pick the left most bag
Picked value is 4
Remaining set is [3, 20, 5, 8, 7, 19, 1]
with 7 bags remaining, it is optimal  to pick the left most bag
Picked value is 3
Remaining set is [20, 5, 8, 7, 19, 1]
with 6 bags remaining, it is optimal  to pick the left most bag
Picked value is 20
Remaining set is [5, 8, 7, 19, 1]
with 5 bags remaining, it is optimal  to pick the left most bag
Picked value is 5
Remaining set is [8, 7, 19, 1]
with 4 b

#### EXAMPLE 1

In [2]:
A=[ 5 , 12, 1, 2 ]

d=len(A)

F , S, D = bags(A)

print(D)

print(A)
print()
print('The optimal value for the starter is',F[d-1][0])
print('The optimal value for the second player is',S[d-1][0])
print()
printing_decisions(A)

[[0. 0. 0. 0.]
 [0. 1. 0. 0.]
 [1. 1. 0. 0.]
 [0. 0. 0. 0.]]
[5, 12, 1, 2]

The optimal value for the starter is 14.0
The optimal value for the second player is 6.0

with 4 bags remaining, it is optimal  to pick the right most bag
Picked value is 2
Remaining set is [5, 12, 1]
with 3 bags remaining, it is optimal  to pick the left most bag
Picked value is 5
Remaining set is [12, 1]
with 2 bags remaining, it is optimal  to pick the left most bag
Picked value is 12
Remaining set is [1]
with 1 bags remaining, it is optimal  to pick the right most bag
Picked value is 1
Remaining set is []


### EXAMPLE 2

In [3]:
A=[7, 15 , 1, 3 , 1, 4]

d=len(A)

F , S, D = bags(A)

print(A)
print()
print('The optimal value for the starter is',F[d-1][0])
print('The optimal value for the second player is',S[d-1][0])
print()
printing_decisions(A)

[7, 15, 1, 3, 1, 4]

The optimal value for the starter is 22.0
The optimal value for the second player is 9.0

with 6 bags remaining, it is optimal  to pick the right most bag
Picked value is 4
Remaining set is [7, 15, 1, 3, 1]
with 5 bags remaining, it is optimal  to pick the left most bag
Picked value is 7
Remaining set is [15, 1, 3, 1]
with 4 bags remaining, it is optimal  to pick the left most bag
Picked value is 15
Remaining set is [1, 3, 1]
with 3 bags remaining, it is optimal  to pick the left most bag
Picked value is 1
Remaining set is [3, 1]
with 2 bags remaining, it is optimal  to pick the left most bag
Picked value is 3
Remaining set is [1]
with 1 bags remaining, it is optimal  to pick the right most bag
Picked value is 1
Remaining set is []


### EXAMPLE FR0M LECTURE

In [4]:
A=[1 , 5,  2, 15 , 1 , 9 , 17, 1]

d=len(A)

F , S, D = bags(A)

print(A)
print()
print('The optimal value for the starter is',F[d-1][0])
print('The optimal value for the second player is',S[d-1][0])
print()
printing_decisions(A)

[1, 5, 2, 15, 1, 9, 17, 1]

The optimal value for the starter is 30.0
The optimal value for the second player is 21.0

with 8 bags remaining, it is optimal  to pick the right most bag
Picked value is 1
Remaining set is [1, 5, 2, 15, 1, 9, 17]
with 7 bags remaining, it is optimal  to pick the right most bag
Picked value is 17
Remaining set is [1, 5, 2, 15, 1, 9]
with 6 bags remaining, it is optimal  to pick the right most bag
Picked value is 9
Remaining set is [1, 5, 2, 15, 1]
with 5 bags remaining, it is optimal  to pick the left most bag
Picked value is 1
Remaining set is [5, 2, 15, 1]
with 4 bags remaining, it is optimal  to pick the left most bag
Picked value is 5
Remaining set is [2, 15, 1]
with 3 bags remaining, it is optimal  to pick the left most bag
Picked value is 2
Remaining set is [15, 1]
with 2 bags remaining, it is optimal  to pick the left most bag
Picked value is 15
Remaining set is [1]
with 1 bags remaining, it is optimal  to pick the right most bag
Picked value is 1
Re

#### If not the left bag is chosen
Then the second player becomes the first and collectes 25; \
more than the 21 possible if the left were chosen.

In [5]:
A=[5,  2, 15 , 1 , 9 , 17, 1]

d=len(A)

F , S, D = bags(A)

print(A)
print()
print('The optimal value for the starter is',F[d-1][0])
print('The optimal value for the second player is',S[d-1][0])
print()
printing_decisions(A)

[5, 2, 15, 1, 9, 17, 1]

The optimal value for the starter is 25.0
The optimal value for the second player is 25.0

with 7 bags remaining, it is optimal  to pick the left most bag
Picked value is 5
Remaining set is [2, 15, 1, 9, 17, 1]
with 6 bags remaining, it is optimal  to pick the right most bag
Picked value is 1
Remaining set is [2, 15, 1, 9, 17]
with 5 bags remaining, it is optimal  to pick the right most bag
Picked value is 17
Remaining set is [2, 15, 1, 9]
with 4 bags remaining, it is optimal  to pick the right most bag
Picked value is 9
Remaining set is [2, 15, 1]
with 3 bags remaining, it is optimal  to pick the left most bag
Picked value is 2
Remaining set is [15, 1]
with 2 bags remaining, it is optimal  to pick the left most bag
Picked value is 15
Remaining set is [1]
with 1 bags remaining, it is optimal  to pick the right most bag
Picked value is 1
Remaining set is []


#### If again 1 was not chosen
This time the original second player gets 25 more; total of 30

In [6]:
A=[ 15 , 1 , 9 , 17, 1]

d=len(A)

F , S, D = bags(A)

print(A)
print()
print('The optimal value for the starter is',F[d-1][0])
print('The optimal value for the second player is',S[d-1][0])
print()
printing_decisions(A)

[15, 1, 9, 17, 1]

The optimal value for the starter is 25.0
The optimal value for the second player is 18.0

with 5 bags remaining, it is optimal  to pick the left most bag
Picked value is 15
Remaining set is [1, 9, 17, 1]
with 4 bags remaining, it is optimal  to pick the left most bag
Picked value is 1
Remaining set is [9, 17, 1]
with 3 bags remaining, it is optimal  to pick the left most bag
Picked value is 9
Remaining set is [17, 1]
with 2 bags remaining, it is optimal  to pick the left most bag
Picked value is 17
Remaining set is [1]
with 1 bags remaining, it is optimal  to pick the right most bag
Picked value is 1
Remaining set is []


In [7]:
A=[5,  2, 15 , 1 , 9 , 17,  3, 6, 7, 9]

d=len(A)

F , S, D = bags(A)

print(A)
print()
print('The optimal value for the starter is',F[d-1][0])
print('The optimal value for the second player is',S[d-1][0])
print()
printing_decisions(A)

[5, 2, 15, 1, 9, 17, 3, 6, 7, 9]

The optimal value for the starter is 42.0
The optimal value for the second player is 32.0

with 10 bags remaining, it is optimal  to pick the right most bag
Picked value is 9
Remaining set is [5, 2, 15, 1, 9, 17, 3, 6, 7]
with 9 bags remaining, it is optimal  to pick the right most bag
Picked value is 7
Remaining set is [5, 2, 15, 1, 9, 17, 3, 6]
with 8 bags remaining, it is optimal  to pick the right most bag
Picked value is 6
Remaining set is [5, 2, 15, 1, 9, 17, 3]
with 7 bags remaining, it is optimal  to pick the left most bag
Picked value is 5
Remaining set is [2, 15, 1, 9, 17, 3]
with 6 bags remaining, it is optimal  to pick the right most bag
Picked value is 3
Remaining set is [2, 15, 1, 9, 17]
with 5 bags remaining, it is optimal  to pick the right most bag
Picked value is 17
Remaining set is [2, 15, 1, 9]
with 4 bags remaining, it is optimal  to pick the right most bag
Picked value is 9
Remaining set is [2, 15, 1]
with 3 bags remaining, it is 

In [8]:
A=[2, 15 , 1 , 9 , 17,  3, 6, 7, 9]
F , S, D = bags(A)
print('The optimal value for the starter is',F[d-1][0])
print('The optimal value for the second player is',S[d-1][0])

B=[5, 2, 15, 1, 9, 17, 3, 6, 7]
F , S, D = bags(B)
print('The optimal value for the starter is',F[d-1][0])
print('The optimal value for the second player is',S[d-1][0])


IndexError: index 9 is out of bounds for axis 0 with size 9

In [ ]:
A=[7,5,2,15,8,1,25,3,2,5]

d=len(A)

F , S, D = bags(A)

print(A)
print()
print('The optimal value for the starter is',F[d-1][0])
print('The optimal value for the second player is',S[d-1][0])
print()
printing_decisions(A)

In [ ]:
A=[2, 15, 8, 1, 25, 3, 2,5]

d=len(A)

F , S, D = bags(A)

print(A)
print()
print('The optimal value for the starter is',F[d-1][0])
print('The optimal value for the second player is',S[d-1][0])
print()
printing_decisions(A)